/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import service.Database;

/**
 *
 * @author irem
 */
public class VeritabanıGUI extends javax.swing.JFrame {

    /**
     * Creates new form VeritabanıGUI
     */
    public VeritabanıGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        geribtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        oybtn = new javax.swing.JButton();
        ligbtn = new javax.swing.JButton();
        takbtn = new javax.swing.JButton();
        getoybtn = new javax.swing.JButton();
        idtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        geribtn.setText("Geri");
        geribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geribtnActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        oybtn.setText("Oyuncu Listele");
        oybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oybtnActionPerformed(evt);
            }
        });

        ligbtn.setText("Lig listele");
        ligbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligbtnActionPerformed(evt);
            }
        });

        takbtn.setText("Takım Listele");
        takbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takbtnActionPerformed(evt);
            }
        });

        getoybtn.setText("Oyuncu getir");
        getoybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getoybtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Oyuncu id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getoybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(geribtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(takbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(oybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ligbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geribtn)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(oybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(takbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ligbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(getoybtn)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geribtnActionPerformed
        new AnasayfaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_geribtnActionPerformed

    private void oybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oybtnActionPerformed
        try ( Connection con = Database.getConnection();) {
            String sql = "SELECT oyuncu_id, oyuncu_ad, oyuncu_boy, oyuncu_kilo, pozisyon, dogum_tarih, milliyet FROM oyuncu";
            try ( PreparedStatement preparedStatement = con.prepareStatement(sql)) {
                try ( ResultSet resultSet = preparedStatement.executeQuery()) {
                    textArea.setText(""); // JTextArea'yı temizle

                    while (resultSet.next()) {
                        int oyuncuId = resultSet.getInt("oyuncu_id");
                        String oyuncuAd = resultSet.getString("oyuncu_ad");
                        int oyuncuBoy = resultSet.getInt("oyuncu_boy");
                        int oyuncuKilo = resultSet.getInt("oyuncu_kilo");
                        String pozisyon = resultSet.getString("pozisyon");
                        String dogumTarih = resultSet.getString("dogum_tarih");
                        String milliyet = resultSet.getString("milliyet");

                        // JTextArea'ya verileri ekleyin
                        textArea.append("Oyuncu ID: " + oyuncuId
                                + ", Ad: " + oyuncuAd
                                + ", Boy: " + oyuncuBoy
                                + ", Kilo: " + oyuncuKilo
                                + ", Pozisyon: " + pozisyon
                                + ", Doğum Tarihi: " + dogumTarih
                                + ", Milliyet: " + milliyet + "\n");
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Veritabanından bilgiler alınamadı.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_oybtnActionPerformed

    private void takbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takbtnActionPerformed
        try ( Connection con = Database.getConnection();) {
            String sql = "SELECT takim_id, takim_ad, kurulus_tarih, takım_ulke FROM takim";
            try ( PreparedStatement preparedStatement = con.prepareStatement(sql)) {
                try ( ResultSet resultSet = preparedStatement.executeQuery()) {
                    textArea.setText(""); // JTextArea'yı temizle

                    while (resultSet.next()) {
                        int takimId = resultSet.getInt("takim_id");
                        String takimAd = resultSet.getString("takim_ad");
                        String kurulusTarih = resultSet.getString("kurulus_tarih");
                        String takimUlke = resultSet.getString("takım_ulke");

                        // JTextArea'ya verileri ekleyin
                        textArea.append("Takım ID: " + takimId
                                + ", Takım Adı: " + takimAd
                                + ", Kuruluş Tarihi: " + kurulusTarih
                                + ", Takım Ülke: " + takimUlke + "\n");
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Veritabanından bilgiler alınamadı.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_takbtnActionPerformed

    private void ligbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligbtnActionPerformed
        try ( Connection con = Database.getConnection();) {
            String sql = "SELECT lig_id, lig_adı, lig_ulke, takim_sayi FROM lig";
            try ( PreparedStatement preparedStatement = con.prepareStatement(sql)) {
                try ( ResultSet resultSet = preparedStatement.executeQuery()) {
                    textArea.setText(""); // JTextArea'yı temizle

                    while (resultSet.next()) {
                        int ligId = resultSet.getInt("lig_id");
                        String ligAdi = resultSet.getString("lig_adı");
                        String ligUlke = resultSet.getString("lig_ulke");
                        int takimSayi = resultSet.getInt("takim_sayi");

                        // JTextArea'ya verileri ekleyin
                        textArea.append("Lig ID: " + ligId
                                + ", Lig Adı: " + ligAdi
                                + ", Lig Ülke: " + ligUlke
                                + ", Takım Sayısı: " + takimSayi + "\n");
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Veritabanından bilgiler alınamadı.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ligbtnActionPerformed

    private void getoybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getoybtnActionPerformed
        try ( Connection con = Database.getConnection();) {
            String sql = "SELECT oyuncu_id, oyuncu_ad, oyuncu_boy, oyuncu_kilo, pozisyon, dogum_tarih, milliyet FROM oyuncu where oyuncu_id=?";
            try ( PreparedStatement preparedStatement = con.prepareStatement(sql)) {
                int oyuncuId = Integer.parseInt(idtf.getText());
                preparedStatement.setInt(1, oyuncuId);

                try ( ResultSet resultSet = preparedStatement.executeQuery()) {
                    textArea.setText(""); // JTextArea'yı temizle

                    while (resultSet.next()) {
                        int id = resultSet.getInt("oyuncu_id");
                        String oyuncuAd = resultSet.getString("oyuncu_ad");
                        int oyuncuBoy = resultSet.getInt("oyuncu_boy");
                        int oyuncuKilo = resultSet.getInt("oyuncu_kilo");
                        String pozisyon = resultSet.getString("pozisyon");
                        String dogumTarih = resultSet.getString("dogum_tarih");
                        String milliyet = resultSet.getString("milliyet");

                        // JTextArea'ya verileri ekleyin
                        textArea.append("Oyuncu ID: " + id
                                + ", Ad: " + oyuncuAd
                                + ", Boy: " + oyuncuBoy
                                + ", Kilo: " + oyuncuKilo
                                + ", Pozisyon: " + pozisyon
                                + ", Doğum Tarihi: " + dogumTarih
                                + ", Milliyet: " + milliyet + "\n");
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Veritabanından bilgiler alınamadı.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_getoybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeritabanıGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeritabanıGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeritabanıGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeritabanıGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeritabanıGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geribtn;
    private javax.swing.JButton getoybtn;
    private javax.swing.JTextField idtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ligbtn;
    private javax.swing.JButton oybtn;
    private javax.swing.JButton takbtn;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
